echo Spinning up the stack...
microk8s kubectl apply -f ./kubernetes.yml
echo Expose cluster port...
microk8s kubectl expose deployment/http-server-deployment --type="NodePort" --port 8081
echo Generate pods data...
microk8s kubectl describe pods | sudo tee /vagrant/pods.data.txt
echo Done. See pods.data.txt.